    <!-- contenido-->
        <div class="col-md-3">
    
        </div>
        
        <div class="col-md-6">
            <div class="panel panel-primario">
                <div class="panel-heading"><h3><?php echo($this->titulo);?></h3></div>
                <div class="panel-body">
                    <div class="col-md-6">
                        <!-- formulario de logeo -->
                        <form class="form-signin" action="#">
                            <h2 class="form-signin-heading">Please sign in</h2>
                            <label for="inputEmail" class="sr-only">Email address</label>
                            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                            <label for="inputPassword" class="sr-only">Password</label>
                            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="remember-me"> Remember me
                                </label>
                            </div>
                            <button class="btn btn-lg btn-success btn-block" type="submit">Sign in</button>

                        </form>
                         <!-- fin formulario de logeo -->
                    </div>
                    <div class="col-md-6">
                         <!-- boton de registrarse -->
                         <h2>Registrate ahora gratis</h2>
                         <span class="glyphicon glyphicon-ok "></span> mira todas tus glucemias<br>
                         <span class="glyphicon glyphicon-ok "></span> oganiza  los registros<br>
                         <span class="glyphicon glyphicon-ok "></span> trabaja tus insulias<br>
                         <span class="glyphicon glyphicon-ok "></span> graficos de tus glucemias<br>
                         <span class="glyphicon glyphicon-ok "></span> graficos de tus insulinas<br>
                        
                        <a id ="registrate" class="btn btn-lg btn-primario btn-block " href="<?php echo(BASE_URL.'register');?>">registrate</a>

                    </div>
                </div>
            </div>
            <div class="col-md-3">
            </div>
        </div> 