<div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="panel panel-primario">
            <div class="panel-heading"><h3><?php echo $this->titulo;?><br><?php echo $this->paciente;?></h3></div>
                <div class="panel-body">
                    
                    <div class="text-center">
						<form action="grafico" method="post" name="form1" role="form" >
							<div class="col-md-3">
							</div>
							<div class="form-group col-md-6">
								<div class="form-group col-md-4">
									<lavel for="fecha1">fecha inicio</lavel>
									<input type="date" class="form-control" name ="fecha1" id="fecha1" placeholder="fecha inicio">
								</div>
								<div class="form-group col-md-4">
									<lavel for="fecha2">fecha final</lavel>
									<input type="date" class="form-control" name ="fecha2" id="fecha2" placeholder="fecha final">
								</div>
								<div class="form-group col-md-4">
									<lavel for="opfecha">horario</lavel>
									<select class="form-control" name ="opfecha" id="opfecha">
										<option value ="selec">-- selecionar momento del dia --</option>

										<option value ="0">otras</option>
                                        <option value ="9">normales</option>
                                        <option value ="10">especiales</option>
										<option value ="1">mañana</option>
										<option value ="2">mediodia</option>
										<option value ="3">merienda</option>
										<option value ="4">cena</option>
										<option value ="5">especial mañana</option>
										<option value ="6">especial mediodia</option>
										<option value ="7">especial cena</option>
										<option value ="8">especial nocturno</option>

									</select>
								</div>
								<input type="submit" class="btn btn-success btn-block" >
							</div>
							<div class="col-md-3">
							</div>
							
						</form>
						
                    <?php echo $this->grafico;?>
					</div>
                    
                        
                    
                </div>
        </div>                    
    </div>
<div class="col-md-1"></div>