
<div class="col-md-2"></div>
    <div class="col-md-8">
        <div class=" panel panel-primario">
            <form enctype ="multipart/form-data" action="insertar_archivo" method="post" name="archivo" role="form" >
                <div class="form-group col-md-6 col-md-offset-3">
                <input type="hidden" name="MAX_FILE_SIZE" value="200000" />
                <lavel for="archivo">archivo de glucemias</lavel>
                <input class="" name="archivo" id="archivo" placeholder="archivo de glucemias" type="file">
                </div>
                <input class="btn btn-success btn-block" type="submit" value="subir archivo">
            </form>
        </div>

    </div>    
<div class="col-md-2"></div>